/**
 * Server Side Rendering
 */
import { APIGatewayEvent } from "aws-lambda";
import * as React from "react";
import { renderToString } from "react-dom/server";

import App from "../App";
import ConfigContext from "../components/ConfigContext";
import config from "./config";
import html from "./html";
import { Stats } from "./types";
//@ts-ignore
import { StaticRouter } from "react-router-dom/server";

/**
 * Server-side rendering
 */
export default async function render(_event: APIGatewayEvent): Promise<string> {
  // console.log("Event", _event);

  // The stats are generated by the Webpack Stats Plugin (`webpack-stats-plugin`)
  const stats = (await import("../../dist/stats.json")) as unknown as Stats;
  const content = renderToString(
    <StaticRouter location={"/"}>
      <ConfigContext.Provider value={config}>
        <App />
      </ConfigContext.Provider>
    </StaticRouter>,
  );
  return html({ stats, content, config });
}
